config/routes.rb
Crowdfunder::Application.routes.draw do
  resources :projects do
    get 'page/:page', action: :index, on: :collection, as: :paginated
    resources :pledges, shallow: true
  end
  
  resources :users

  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  resources :sessions

  namespace :my do
    resources :projects do
      resources :images, shallow: true
    end
  end

  root 'static_pages#home'

  

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user, :project, presence: true
  validates :amount,
  	presence: true,
  	numericality: true

  validate :validate_amount_greater_than_zero

  protected

  		def validate_amount_greater_than_zero
				if amount && amount < 0
					errors.add :amount, "must be greater than 0"
				end
			end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :pledges
  has_many :images
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :projects
  has_many :pledges
  has_many :images, through: :projects
  attr_accessor :password, :password_confirmation

  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my/images_controller.rb
class My::ImagesController < ApplicationController
  before_filter :load_project

  def index
    @images = @project.images
  end

  def new
    @image = @project.images.build
  end

  def create
    @image = @project.images.build(
      name: params[:image][:name],
      description: params[:image][:description],
      image: params[:image][:image],
      user: current_user
    )

    if @image.save
      flash[:notice] = "Success"
      redirect_to my_project_images_path(@project)
    else
      flash.now[:error] = "Sorry, attachment must be an image."
      render 'new'
    end
  end

  protected 

      def load_project
        @project = Project.find(params[:project_id])
      end

end

app/controllers/my/projects_controller.rb
class My::ProjectsController < ApplicationController
  before_filter :require_login

  def index
    @projects = Project.where(user: current_user)
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(
      title: params[:project][:title],
      teaser: params[:project][:teaser],
      description: params[:project][:description],
      goal: params[:project][:goal],
      user: current_user
      )

    if @project.save
      redirect_to my_projects_path, notice: "Success!"
    else
      flash.now[:error] = "Sorry, something went wrong."
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
    if @project.user != current_user
      flash[:error] = "You cannot edit other users' projects"
      redirect_to projects_path
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(
      title: params[:project][:title],
      teaser: params[:project][:teaser],
      description: params[:project][:description],
      goal: params[:project][:goal],
      user: current_user
      )
      redirect_to my_projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end

  protected 
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_filter :load_project
  before_filter :require_login, only: [:new, :create]

	def index
	end

	def new
		@pledge = Pledge.new
	end

	def create
		@pledge = Pledge.new(
			user_id: current_user.id, 
			project_id: @project.id,
			amount: params[:pledge][:amount])
		
		if @pledge.save
			flash[:notice] = "Thanks for supporting this project!"
			UserMailer.new_pledge(current_user, @project, @pledge).deliver
			UserMailer.you_got_paid(@project.user, @project, @pledge).deliver
			redirect_to @project
		else
			render 'new'
		end
	end

	def destroy
	end

	protected

			def load_project
				@project = Project.find(params[:project_id])
			end

			def not_authenticated
				redirect_to login_path, alert: "You must login to pledge!"
			end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  	@projects = Project.order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
  	@project = Project.find(params[:id])
  end
 #  def new
	# @n_project = Project.new
 #  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def index
	end

	def new
	end

	def create
		user = login(params[:email], params[:password])

		if user
			flash[:notice] = "Welcome back!"
			redirect_back_or_to root_url
		else
			flash.now[:error] = "Email or password not found"
			render 'new'
		end
	end

	def destroy
		logout
		flash[:notice] = "Bye!"
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)

    if @user.save
      flash[:notice] = "Account Created!"
      redirect_to root_path
  	else
      flash.now[:alert] = "Try again!"
      render 'new'
    end
  end

  private

  		def user_params
  			params.require(:user).permit(:first_name, :last_name, :email, :password)
  		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my/images_helper.rb
module My::ImagesHelper
end

app/helpers/my/projects_helper.rb
module My::ProjectsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <% if current_page? root_path %>
        <%= link_to 'Civignite', '#', class: "brand" %>
      <% else %>
        <%= link_to 'Civignite', root_path, class: "brand" %>
      <% end %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="<%= 'active' if current_page? root_path %>">
            <%= link_to 'Home', :root %>
          </li>
          <li class="<%= 'active' if (current_page? projects_path) %>">
            <%= link_to 'Projects', :projects %>
          </li>          
          <% if logged_in? %>
            <li class="<%= 'active' if (current_page? my_projects_path) || (current_page? new_my_project_path) %>">
              <%= link_to 'My Projects', :my_projects %>
            </li>
            <li>
              <%= link_to 'Log Out', logout_path, method: :delete %>
            </li>
          <% else %>
            <li class="<%= 'active' if (current_page? new_user_path) %>">
              <%= link_to 'Sign up', :new_user %>
            </li>
            <li class="<%= 'active' if (current_page? new_session_path) %>">
              <%= link_to 'Log in', :new_session %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Civigite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render "layouts/header" %>

		<% flash.each do |type, msg| %>
			<div class="<%= type %>">
			  <%= msg %>
			</div>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/my/images/index.html.erb
<%= link_to "New Image", new_my_project_image_path(@project) %>
<% @images.each do |image| %>
	<div class="project-img">
		<%= image_tag image.image_url.to_s %>
	</div>
<% end %> 

app/views/my/images/new.html.erb
<h1>Upload a photo for <%= @project.title %></h1>
<%= form_for [:my, @project, @image], html: { multipart: true } do |f| %>
  <div class="field">
  	<%= f.label :name %>
  	<%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :description %>
  	<%= f.text_field :description %>
  </div>
  <div class="field">
  	<%= f.file_field :image %>
  </div>
  <div class="actions">
  	<%= f.submit "Upload photo" %>
  </div>

<% end %>

app/views/my/projects/create.html.erb
<h1>My::Projects#create</h1>
<p>Find me in app/views/my/projects/create.html.erb</p>

app/views/my/projects/destroy.html.erb
<h1>My::Projects#destroy</h1>
<p>Find me in app/views/my/projects/destroy.html.erb</p>

app/views/my/projects/edit.html.erb
<h1>Edit <%= @project.title %></h1>
<%= link_to "Manage Images", my_project_images_path(@project) %>
<%= form_for [:my, @project] do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :teaser %>
		<%= f.text_field :teaser %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :goal %>
		<%= f.number_field :goal %>
	</div>
	<div class="actions">
		<%= f.submit "Update project" %>
	</div>
<% end %>
<%= button_to "Delete Project", [:my, @project], method: :delete, data: { confirm: "Are you sure?" }, class: "btn-danger"%>

app/views/my/projects/index.html.erb
<h1>My Projects</h1>
<%= link_to 'New Project', :new_my_project %>	
<% @projects.each do |project| %>
	<div class="project">
		<h3><%= link_to project.title, [:my, project] %></h3>
		<h5><%= project.teaser %></h5>
		<p><%= project.description %></p>
	</div>
<% end %>

app/views/my/projects/new.html.erb
<h1>New Project</h1>
<%= form_for [:my, @project] do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :teaser %>
		<%= f.text_field :teaser %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :goal %>
		<%= f.number_field :goal %>
	</div>
	<div class="actions">
		<%= f.submit "Create Project" %>
	</div>
<% end %>

app/views/my/projects/show.html.erb
<h1><%= @project.title %></h1>
<h3>$<%= @project.goal %></h3>
<h5><%= @project.teaser %></h5>
<p><%= @project.description %></p>
<%= link_to "Edit Project", edit_my_project_path(@project) %>

app/views/my/projects/update.html.erb
<h1>My::Projects#update</h1>
<p>Find me in app/views/my/projects/update.html.erb</p>

app/views/pledges/new.html.erb
<h1>Back a </h1>
<%= form_for [@project, @pledge] do |f| %>
  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
  	<%= f.submit "Pledge now!" %>
  </div>
<% end %>

app/views/projects/index.html.erb
<h1>All projects</h1>
<%= paginate @projects %>
<% @projects.each do |project| %>
	<div class="project">
		<h3><%= link_to project.title, project %></h3>
		<h5><%= project.teaser %></h5>
		<p><%= project.description %></p>
		<p>Goal: <%= project.goal %></p>
	</div>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<div class="actions">
	<%= link_to "Support this project!", new_project_pledge_path(@project) %>
</div>

app/views/static_pages/home.html.erb
<div></div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
	<div class="field">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Create Account" %>
	</div>
<% end %>